version: '3.8'

services:
  # Base de données
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rdgtt_portail
      POSTGRES_USER: rdgtt_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rdgtt-network
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rdgtt_user -d rdgtt_portail"]
      interval: 30s
      timeout: 10s

  # Service Discovery
  consul:
    image: hashicorp/consul:1.15
    command: agent -server -bootstrap-expect=1 -client=0.0.0.0 -ui -bind=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      - rdgtt-network
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway
  traefik:
    image: traefik:v3.5
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.emailfile=/run/secrets/acme_email"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt
    networks:
      - rdgtt-network
    secrets:
      - acme_email

  # Services
  usager-service:
    build: ./usager-service
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rdgtt_portail
      SPRING_DATASOURCE_USERNAME: rdgtt_user
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    networks:
      - rdgtt-network
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
    secrets:
      - db_password
      - jwt_secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usager.rule=Host(`168.119.123.247`) && PathPrefix(`/api/usager`)"
      - "traefik.http.services.usager.loadbalancer.server.port=8081"

  admin-service:
    build: ./admin-service
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rdgtt_portail
      SPRING_DATASOURCE_USERNAME: rdgtt_user
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    networks:
      - rdgtt-network
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
    secrets:
      - db_password
      - jwt_secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`168.119.123.247`) && PathPrefix(`/api/admin`)"
      - "traefik.http.services.admin.loadbalancer.server.port=8082"

  permis-service:
    build: ./permis-service
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rdgtt_portail
      SPRING_DATASOURCE_USERNAME: rdgtt_user
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    networks:
      - rdgtt-network
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
    secrets:
      - db_password
      - jwt_secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.permis.rule=Host(`168.119.123.247`) && PathPrefix(`/api/permis`)"
      - "traefik.http.services.permis.loadbalancer.server.port=8083"

  auto-ecole-service:
    build: ./auto-ecole-service
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rdgtt_portail
      SPRING_DATASOURCE_USERNAME: rdgtt_user
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    networks:
      - rdgtt-network
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
    secrets:
      - db_password
      - jwt_secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auto-ecole.rule=Host(`168.119.123.247`) && PathPrefix(`/api/auto-ecole`)"
      - "traefik.http.services.auto-ecole.loadbalancer.server.port=8084"

  frontend:
    build: ./frontend
    networks:
      - rdgtt-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`168.119.123.247`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

# Define secrets
secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  acme_email:
    file: ./secrets/acme_email.txt

# Define volumes
volumes:
  postgres_data:
  traefik_data:

# Define networks
networks:
  rdgtt-network:
    driver: bridge