server:
  port: 8085

spring:
  application:
    name: admin-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/rdgtt_portail
    username: rdgtt_user
    password: rdgtt_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: admin-service
        instance-id: admin-service-1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    ga.rdgtt.admin: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
